### ISSUE TITLE
Quickstart errors following README with sample data

### ISSUE THREAD

**Issue by MarcelBP** [modal-labs/llm-finetuning#20]
> git clone https://github.com/modal-labs/llm-finetuning.git
cd llm-finetuning

> modal run --detach src.train

Note that running a local entrypoint in detached mode only keeps the last triggered Modal function alive after the parent process has been killed or disconnected.
✓ Initialized. View run at https://modal.com/...../MAOLn2nXinIjRIL64vxP
⠏ Creating objects...2023-12-22T15:40:46+0200 Mount of '/home/WorkSpace/modal/llm-finetuning/src' is empty.
✓ Created objects.
├── 🔨 Created mount /home/WorkSpace/modal/llm-finetuning/src
├── 🔨 Created train.
├── 🔨 Created merge.
├── 🔨 Created launch.
└── 🔨 Created Inference.completion.

==========
== CUDA ==
==========

CUDA Version 11.8.0

.....
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

Traceback (most recent call last):
Runner failed with exception: ModuleNotFoundError("No module named 'src'")
  File "/pkg/modal/_container_entrypoint.py", line 336, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 792, in main
    imp_fun = import_function(
  File "/pkg/modal/_container_entrypoint.py", line 659, in import_function
    module = importlib.import_module(function_def.module_name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src'

**Comment by MarcelBP** [comment]
Error avoided by running outside the python Virtualenv.
